name: Framework python package

on:
  push:
    tags:
      - "bk-plugin-framework-v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.8.5

      - name: Package and Publish
        run: |
          cd bk-plugin-framework
          poetry build -vvv
          poetry config pypi-token.pypi ${{ secrets.FRAMEWORK_PYPI_TOKEN }}
          poetry publish
